### ISSUE TITLE
Support for Parrot 

### ISSUE THREAD

**Issue by greenskii** [NextDom/plugin-MiFlora#35]
| UUID | Handle
-- | -- | --
LIVE_SERVICE | 39e1fa00-84a8-11e2-afba-0002a5d5c51b | #N/A
CALIBRATION_SERVICE | 39e1fe00-84a8-11e2-afba-0002a5d5c51b | #N/A
  |   | #N/A
SUNLIGHT | 39e1fa01-84a8-11e2-afba-0002a5d5c51b | 0x0025
SOIL_EC | 39e1fa02-84a8-11e2-afba-0002a5d5c51b | 0x0031
SOIL_TEMPERATURE | 39e1fa03-84a8-11e2-afba-0002a5d5c51b | 0x0034
AIR_TEMPERATURE | 39e1fa04-84a8-11e2-afba-0002a5d5c51b | 0x0037
SOIL_MOISTURE | 39e1fa05-84a8-11e2-afba-0002a5d5c51b | 0x003a
LIVE_MODE_PERIOD | 39e1fa06-84a8-11e2-afba-0002a5d5c51b | 0x003d
LED | 39e1fa07-84a8-11e2-afba-0002a5d5c51b | 0x003f
LAST_MOVE_DATE | 39e1fa08-84a8-11e2-afba-0002a5d5c51b | #N/A
CALIBRATED_SOIL_MOISTURE | 39e1fa09-84a8-11e2-afba-0002a5d5c51b | 0x0041
CALIBRATED_AIR_TEMPERATURE | 39e1fa0a-84a8-11e2-afba-0002a5d5c51b | 0x0044
CALIBRATED_DLI | 39e1fa0b-84a8-11e2-afba-0002a5d5c51b | 0x0047
CALIBRATED_EA | 39e1fa0c-84a8-11e2-afba-0002a5d5c51b | #N/A
CALIBRATED_ECB | 39e1fa0d-84a8-11e2-afba-0002a5d5c51b | #N/A
CALIBRATED_EC_POROUS | 39e1fa0e-84a8-11e2-afba-0002a5d5c51b | #N/A
  |   | #N/A
FRIENDLY_NAME | 39e1fe03-84a8-11e2-afba-0002a5d5c51b | 0x0070
COLOR | 39e1fe04-84a8-11e2-afba-0002a5d5c51b | 0x0072
CLOCK_SERVICE | 39e1fd00-84a8-11e2-afba-0002a5d5c51b | #N/A
CLOCK_CURRENT_TIME | 39e1fd01-84a8-11e2-afba-0002a5d5c51b | 0x0069
  |   | #N/A
HISTORY_SERVICE | 39e1fc00-84a8-11e2-afba-0002a5d5c51b | #N/A
HISTORY_NB_ENTRIES | 39e1fc01-84a8-11e2-afba-0002a5d5c51b | 0x004f
HISTORY_LASTENTRY_IDX | 39e1fc02-84a8-11e2-afba-0002a5d5c51b | 0x0051
HISTORY_TRANSFER_START_IDX | 39e1fc03-84a8-11e2-afba-0002a5d5c51b | 0x0053
HISTORY_CURRENT_SESSION_ID | 39e1fc04-84a8-11e2-afba-0002a5d5c51b | 0x0055
HISTORY_CURRENT_SESSION_START_IDX | 39e1fc05-84a8-11e2-afba-0002a5d5c51b | 0x0057
HISTORY_CURRENT_SESSION_PERIOD | 39e1fc06-84a8-11e2-afba-0002a5d5c51b | 0x0059

**Comment by rjullien** [comment]
Ok je regarde

**Comment by rjullien** [comment]
http://developer.parrot.com/docs/FlowerPower/FlowerPower-BLE.pdf
https://github.com/Parrot-Developers/node-flower-power

**Comment by rjullien** [comment]
J ai reussi a recuperer la temperature de maniere assez coherente avec l'appli.

**Comment by rjullien** [comment]
J ai publie mon script python avec les commentaires sur ma mesure ce soir.
https://github.com/rjullien/plugin-MiFlora/blob/Feature-Parrot/resources/GetParrotFlowerData.py

**Comment by rjullien** [comment]
UUID Description Value to display                                      handle
0x2A19 battery                                                            —> 0x004c 
0x2A00 name                                                               —> 0x0003 
0xFA01 Light characteristic_value                                —> 0x0025
0xFA02 Soil EC (characteristic_value * 3.3) / (211 -1)   —> 0x0029
0xFA03 Soil Temp (characteristic_value * 3.3) / (211 -1) —> 0x002d
0xFA04 Air Temp (characteristic_value * 3.3) / (211 -1)   —> 0x0031
0xFA05 Soil VWC (characteristic_value * 3.3) / (211 -1) —> 0x0035

var LIVE_MODE_PERIOD_UUID                   = '39e1fa0684a811e2afba0002a5d5c51b';
var LED_UUID                                = '39e1fa0784a811e2afba0002a5d5c51b';
var LAST_MOVE_DATE_UUID                     = '39e1fa0884a811e2afba0002a5d5c51b';
var CALIBRATED_SOIL_MOISTURE_UUID           = '39e1fa0984a811e2afba0002a5d5c51b’;  —> 0x003f
var CALIBRATED_AIR_TEMPERATURE_UUID         = '39e1fa0a84a811e2afba0002a5d5c51b’; —> 0x0043
var CALIBRATED_DLI_UUID                     = '39e1fa0b84a811e2afba0002a5d5c51b’; —> 0x0047
var CALIBRATED_EA_UUID                      = '39e1fa0c84a811e2afba0002a5d5c51b’; —> ???
var CALIBRATED_ECB_UUID                     = '39e1fa0d84a811e2afba0002a5d5c51b’; —> ???
var CALIBRATED_EC_POROUS_UUID               = '39e1fa0e84a811e2afba0002a5d5c51b’; —> ???

**Comment by rjullien** [comment]
Mac add reserved for Parrot
A0143D PARROT SA
903AE6 PARROT SA 
9003B7 PARROT SA 
00267E PARROT SA 
00121C PARROT SA

**Comment by rjullien** [comment]
add firmware version
0x2A23 System    ID8    bytes    frameRead
0x2A26 Firmware    revisionUTF8    StringRead
0x2A25 Serial    NumberUTF8    StringRead
0x2A27 Hardware    revision(Bootloader    version)UTF8    StringRead

**Comment by rjullien** [comment]
handle = 0x0002, char properties = 0x0e, char value handle = 0x0003, uuid = 00002a00-0000-1000-8000-00805f9b34fb
handle = 0x0004, char properties = 0x02, char value handle = 0x0005, uuid = 00002a01-0000-1000-8000-00805f9b34fb
handle = 0x0006, char properties = 0x0a, char value handle = 0x0007, uuid = 00002a02-0000-1000-8000-00805f9b34fb
handle = 0x0008, char properties = 0x0a, char value handle = 0x0009, uuid = 00002a03-0000-1000-8000-00805f9b34fb
handle = 0x000a, char properties = 0x02, char value handle = 0x000b, uuid = 00002a04-0000-1000-8000-00805f9b34fb
handle = 0x000d, char properties = 0x20, char value handle = 0x000e, uuid = 00002a05-0000-1000-8000-00805f9b34fb
handle = 0x0011, char properties = 0x02, char value handle = 0x0012, uuid = 00002a23-0000-1000-8000-00805f9b34fb
handle = 0x0013, char properties = 0x02, char value handle = 0x0014, uuid = 00002a24-0000-1000-8000-00805f9b34fb
handle = 0x0015, char properties = 0x02, char value handle = 0x0016, uuid = 00002a25-0000-1000-8000-00805f9b34fb
handle = 0x0017, char properties = 0x02, char value handle = 0x0018, uuid = 00002a26-0000-1000-8000-00805f9b34fb
handle = 0x0019, char properties = 0x02, char value handle = 0x001a, uuid = 00002a27-0000-1000-8000-00805f9b34fb
handle = 0x001b, char properties = 0x02, char value handle = 0x001c, uuid = 00002a28-0000-1000-8000-00805f9b34fb
handle = 0x001d, char properties = 0x02, char value handle = 0x001e, uuid = 00002a29-0000-1000-8000-00805f9b34fb
handle = 0x001f, char properties = 0x02, char value handle = 0x0020, uuid = 00002a2a-0000-1000-8000-00805f9b34fb
handle = 0x0021, char properties = 0x02, char value handle = 0x0022, uuid = 00002a50-0000-1000-8000-00805f9b34fb
handle = 0x0024, char properties = 0x12, char value handle = 0x0025, uuid = 39e1fa01-84a8-11e2-afba-0002a5d5c51b
handle = 0x0028, char properties = 0x12, char value handle = 0x0029, uuid = 39e1fa02-84a8-11e2-afba-0002a5d5c51b
handle = 0x002c, char properties = 0x12, char value handle = 0x002d, uuid = 39e1fa03-84a8-11e2-afba-0002a5d5c51b
handle = 0x0030, char properties = 0x12, char value handle = 0x0031, uuid = 39e1fa04-84a8-11e2-afba-0002a5d5c51b
handle = 0x0034, char properties = 0x12, char value handle = 0x0035, uuid = 39e1fa05-84a8-11e2-afba-0002a5d5c51b
handle = 0x0038, char properties = 0x0a, char value handle = 0x0039, uuid = 39e1fa06-84a8-11e2-afba-0002a5d5c51b
handle = 0x003b, char properties = 0x0a, char value handle = 0x003c, uuid = 39e1fa07-84a8-11e2-afba-0002a5d5c51b
handle = 0x003e, char properties = 0x12, char value handle = 0x003f, uuid = 39e1fa09-84a8-11e2-afba-0002a5d5c51b
handle = 0x0042, char properties = 0x12, char value handle = 0x0043, uuid = 39e1fa0a-84a8-11e2-afba-0002a5d5c51b
handle = 0x0046, char properties = 0x12, char value handle = 0x0047, uuid = 39e1fa0b-84a8-11e2-afba-0002a5d5c51b
handle = 0x004b, char properties = 0x12, char value handle = 0x004c, uuid = 00002a19-0000-1000-8000-00805f9b34fb
handle = 0x004f, char properties = 0x02, char value handle = 0x0050, uuid = 39e1fc01-84a8-11e2-afba-0002a5d5c51b
handle = 0x0053, char properties = 0x02, char value handle = 0x0054, uuid = 39e1fc02-84a8-11e2-afba-0002a5d5c51b
handle = 0x0057, char properties = 0x0a, char value handle = 0x0058, uuid = 39e1fc03-84a8-11e2-afba-0002a5d5c51b
handle = 0x005b, char properties = 0x02, char value handle = 0x005c, uuid = 39e1fc04-84a8-11e2-afba-0002a5d5c51b
handle = 0x005f, char properties = 0x02, char value handle = 0x0060, uuid = 39e1fc05-84a8-11e2-afba-0002a5d5c51b
handle = 0x0063, char properties = 0x02, char value handle = 0x0064, uuid = 39e1fc06-84a8-11e2-afba-0002a5d5c51b
handle = 0x0068, char properties = 0x10, char value handle = 0x0069, uuid = 39e1fb01-84a8-11e2-afba-0002a5d5c51b
handle = 0x006c, char properties = 0x12, char value handle = 0x006d, uuid = 39e1fb02-84a8-11e2-afba-0002a5d5c51b
handle = 0x0070, char properties = 0x0a, char value handle = 0x0071, uuid = 39e1fb03-84a8-11e2-afba-0002a5d5c51b
handle = 0x0073, char properties = 0x0a, char value handle = 0x0074, uuid = 39e1fb04-84a8-11e2-afba-0002a5d5c51b
handle = 0x0077, char properties = 0x02, char value handle = 0x0078, uuid = 39e1fd01-84a8-11e2-afba-0002a5d5c51b
handle = 0x007b, char properties = 0x02, char value handle = 0x007c, uuid = 39e1fe01-84a8-11e2-afba-0002a5d5c51b
handle = 0x007e, char properties = 0x02, char value handle = 0x007f, uuid = 39e1fe02-84a8-11e2-afba-0002a5d5c51b
handle = 0x0081, char properties = 0x02, char value handle = 0x0082, uuid = 39e1fe03-84a8-11e2-afba-0002a5d5c51b
handle = 0x0084, char properties = 0x02, char value handle = 0x0085, uuid = 39e1fe04-84a8-11e2-afba-0002a5d5c51b
handle = 0x0087, char properties = 0x0a, char value handle = 0x0088, uuid = 39e1fe06-84a8-11e2-afba-0002a5d5c51b
handle = 0x008a, char properties = 0x0a, char value handle = 0x008b, uuid = 39e1fd81-84a8-11e2-afba-0002a5d5c51b
handle = 0x008c, char properties = 0x0a, char value handle = 0x008d, uuid = 39e1fd85-84a8-11e2-afba-0002a5d5c51b
handle = 0x008e, char properties = 0x0a, char value handle = 0x008f, uuid = 39e1fd84-84a8-11e2-afba-0002a5d5c51b
handle = 0x0090, char properties = 0x0a, char value handle = 0x0091, uuid = 39e1fd83-84a8-11e2-afba-0002a5d5c51b
handle = 0x0092, char properties = 0x0a, char value handle = 0x0093, uuid = 39e1fd82-84a8-11e2-afba-0002a5d5c51b
handle = 0x0094, char properties = 0x12, char value handle = 0x0095, uuid = 39e1fd86-84a8-11e2-afba-0002a5d5c51b
handle = 0x0098, char properties = 0x0e, char value handle = 0x0099, uuid = f000ffc1-0451-4000-b000-000000000000
handle = 0x009b, char properties = 0x0e, char value handle = 0x009c, uuid = f000ffc2-0451-4000-b000-000000000000
pi@raspberrypi:~ $

**Comment by greenskii** [comment]
[UUID.pdf](https://github.com/NextDom/plugin-MiFlora/files/2009011/UUID.pdf)
