### ISSUE TITLE
Installation des dépendances -> Failed

### ISSUE THREAD

**Issue by slobberbone** [NextDom/plugin-MiFlora#68]
## Description
Les dépendances ne s'installent plus ...

/bin/bash: /var/www/html/plugins/MiFlora/core/class/../../resources/install.sh: No such file or directory

## Etapes à reproduire (pour les bugs)
1.Installer la branche master depuis AlternativeMarketForJeedom
2.Activer le plugin
3.Dépendances non installées
4.Relancer -> erreur

## Environnement:
* **Version Jeedom**: 3.2.7
* **Plateforme**:RPI3
* **Version du Plugin**: af611c9b3f4c07efa8d1af6666cd31a888c02c18

**Comment by slobberbone** [comment]
Il il ya maintenant que le fichier : install_remote.sh ... surement celui là à appeler ? si c le cas , je peux PR !

**Comment by slobberbone** [comment]
Ce qui est étonnant c'est que le fichier à été ajouté en beta ... pas master hors, j'ai installé master normalement ...

**Comment by slobberbone** [comment]
oups ... ne pas faire ça, je viens de crasher mon jeedom ...

**Comment by rjullien** [comment]
Dsl, pb de .gitignore, parfait chez moi mais pas commit dans git. Fixed dans Master, Stable et Beta

**Comment by rjullien** [comment]
install_remote.sh --> pour les antennes. 
Pk ca a crash to jeedom ?
