### ISSUE TITLE
Identifiant matériel incorrect pour Parrot Pot

### ISSUE THREAD

**Issue by rouxton** [NextDom/plugin-MiFlora#71]
Les (en tous les cas miens, achetés il y a un an) Parrot Pot ne sont pas correctement identifiés par le code. 
Le pot renvoi l'identifiant "Parrot pot" alors que dans le code (class.php) on matche sur "Flower Pot"
Je ne sais pas si cela a changé (peut être modifié suite à upgrade firmware des pots) ou si c'est une erreur depuis le début mais la modification permet de corriger les problèmes dans mon cas.

MiFlora version : 2019-05-02 
Jeedom : 3.3.24

Merci

**Comment by rjullien** [comment]
Probleme corrige avec une nouvelle version (cf change log)
