### ISSUE TITLE
Compatibilité jeedom v4? Object not found

### ISSUE THREAD

**Issue by abdelhadj** [NextDom/plugin-MiFlora#83]
## Description
Compatibilité Jeedom v4?
## Etapes à reproduire (pour les bugs)
1.Bonjour, j'ai installé Jeedom sur un Raspi4, lorsque je sélection le plugin, j'obtiens le message  class 'object' not found..
d'après quelques recherches c'est lié à la compatibilité avec la V4, il est recommandé de contacté l'auteur :p 
apparemment faut changer Object à jeeObject?!

Merci d'avance pour l'aide

## Environnement:
* **Version Jeedom**: 4.1.28
* **Plateforme**: Raspberry 4
* **Version du Plugin**: ?

**Comment by Gis70** [comment]
Salut oui c'est ça, je viens de corriger le plugin en master tu peux tester et me dire si c'est OK ?

**Comment by abdelhadj** [comment]
bonjour, je peux toujours l'installer via le market? j'obtiens l'erreur suivante maintenant
Fichier introuvable : /var/www/html/core/php/../../core/js/plugin.ajax.js

**Comment by Gis70** [comment]
Pas sûr, il faut peut être attendre 24h. Il t'a proposé une maj ?

**Comment by abdelhadj** [comment]
La mise à jour de 3.0.x en 3.1.0 nécessite de relancer les dépendances (local + antennes) même si elles apparaissent vertes, ce n est pas necessaire si la version etait deja >= 3.1.0

on parle de quelles dépendances?

**Comment by Gis70** [comment]
les paquets dont le plugin à besoin.

**Comment by Gis70** [comment]
FIx fait
